### ISSUE TITLE
Fix dependencies in pom.xml

### ISSUE THREAD

**Issue by rsignell-usgs** [noaaroland/uafnciso#3]
I tried building this with maven and it failed:
```
git clone https://github.com/noaaroland/uafnciso.git
cd uafnciso
docker run -it --rm --name my-maven-project -v "$PWD":/usr/src/mymaven -w /usr/src/mymaven maven:3.3.9-jdk-8 mvn clean install
```
The error is with failed dependencies:
```
[ERROR] Failed to execute goal on project ncISO: Could not resolve dependencies for project isoConverter:ncISO:jar:1.2.1: 
The following artifacts could not be resolved: edu.ucar:cdm:jar:4.6.0-SNAPSHOT, edu.ucar:thredds:jar:4.3.9-SNAPSHOT, 
edu.ucar:bufr:jar:4.6.0-SNAPSHOT, edu.ucar:clcommon:jar:4.6.0-SNAPSHOT, edu.ucar:grib:jar:4.6.0-SNAPSHOT, 
edu.ucar:netcdf4:jar:4.6.0-SNAPSHOT, edu.ucar:opendap:jar:4.6.0-SNAPSHOT, edu.ucar:visadCdm:jar:4.6.0-SNAPSHOT: Could not find artifact edu.ucar:cdm:jar:4.6.0-SNAPSHOT in unidata-releases (https://artifacts.unidata.ucar.edu/content/repositories/unidata-releases/) 
```
likely because none of these snapshots exist anymore?    
The artifacts in there are at 4.6.8....

And after we fix the version problem, I see there is a dependency on `thredds`, which I don't see any more at:
https://artifacts.unidata.ucar.edu/content/repositories/unidata-releases/edu/ucar/

@lesserwhirls, did `thredds` become `tds`?

**Comment by lesserwhirls** [comment]
@rsignell-usgs yes, the `thredds` artifact should now be `tds`. No idea about the snapshots, but I'd go ahead and use the `4.6.8` release artifacts.

**Comment by rsignell-usgs** [comment]
Switching everything that said `blah-blah-SNAPSHOT` to `4.6.8` and changing `thredds` to `tds`, I now only get ONE error!
```
[ERROR] Failed to execute goal on project ncISO: Could not resolve dependencies for project isoConverter:ncISO:jar:1.2.1: Could not find artifact edu.ucar:tds:jar:4.6.8 in unidata-releases (https://artifacts.unidata.ucar.edu/content/repositories/unidata-releases/) -> [Help 1]

My pom.xml looks like this now.  Shouldn't that work?
```
        <dependency>
            <groupId>edu.ucar</groupId>
            <artifactId>tds</artifactId>
            <version>4.6.8</version>
            <scope>compile</scope>
        </dependency>

```

**Comment by lesserwhirls** [comment]
My bad - give `thredds-parent` a try instead of `tds`.

**Comment by rsignell-usgs** [comment]
@lesserwhirls , ooh, now that you've fixed the pom.xml on ThreddsISO, can you fix the pom.xml for the standalone version here? https://github.com/noaaroland/uafnciso/blob/master/pom.xml

BTW, switching to `thredds-parent` gave basically the same error: 
```
[ERROR] Failed to execute goal on project ncISO: 
Could not resolve dependencies for project isoConverter:ncISO:jar:1.2.1: 
Could not find artifact edu.ucar:thredds-parent:jar:4.6.8 in unidata-releases 
(https://artifacts.unidata.ucar.edu/content/repositories/unidata-releases/) -> [Help 1]
```

**Comment by lesserwhirls** [comment]
Sure thing. Just made a PR.

**Comment by noaaroland** [comment]
I updated the pom myself. Thanks.
